-- Leave request storage for the TimeTrack Manager Portal.
-- Run this migration in the Supabase SQL Editor.

create table if not exists public.leave_requests (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    leave_type text not null,
    start_date date not null,
    end_date date not null,
    reason text,
    status text not null default 'pending',
    created_at timestamptz not null default now(),
    reviewed_at timestamptz,
    reviewed_by uuid references auth.users(id) on delete set null,
    constraint leave_requests_status_check
        check (status in ('pending', 'approved', 'rejected')),
    constraint leave_requests_date_check
        check (end_date >= start_date)
);

alter table public.leave_requests enable row level security;

grant select on public.leave_requests to authenticated;
grant update (status, reviewed_at, reviewed_by)
on public.leave_requests
to authenticated;

create policy "Managers and admins can view leave requests"
on public.leave_requests
for select
to authenticated
using (
    exists (
        select 1
        from public.profiles
        where profiles.id = auth.uid()
          and profiles.role in ('manager', 'admin')
    )
);

create policy "Employees can view their own leave requests"
on public.leave_requests
for select
to authenticated
using (auth.uid() = user_id);

create policy "Employees can submit their own leave requests"
on public.leave_requests
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Managers and admins can review leave requests"
on public.leave_requests
for update
to authenticated
using (
    exists (
        select 1
        from public.profiles
        where profiles.id = auth.uid()
          and profiles.role in ('manager', 'admin')
    )
)
with check (
    status in ('pending', 'approved', 'rejected')
    and exists (
        select 1
        from public.profiles
        where profiles.id = auth.uid()
          and profiles.role in ('manager', 'admin')
    )
);