-- Centralized attendance storage for TimeTrack.
-- Run this migration in the Supabase SQL Editor for the project used by both apps.

create table if not exists public.attendance (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    date date not null,
    time_in timestamptz,
    break_in timestamptz,
    break_out timestamptz,
    time_out timestamptz,
    created_at timestamptz not null default now(),
    constraint attendance_user_date_key unique (user_id, date)
);

alter table public.attendance enable row level security;

create policy "Employees can view their own attendance"
on public.attendance
for select
to authenticated
using (
    (select auth.uid()) = user_id
    and exists (
        select 1
        from public.profiles
        where profiles.id = (select auth.uid())
          and profiles.role = 'employee'
    )
);

create policy "Employees can create their own attendance"
on public.attendance
for insert
to authenticated
with check (
    (select auth.uid()) = user_id
    and exists (
        select 1
        from public.profiles
        where profiles.id = (select auth.uid())
          and profiles.role = 'employee'
    )
);

create policy "Employees can update their own attendance"
on public.attendance
for update
to authenticated
using (
    (select auth.uid()) = user_id
    and exists (
        select 1
        from public.profiles
        where profiles.id = (select auth.uid())
          and profiles.role = 'employee'
    )
)
with check (
    (select auth.uid()) = user_id
    and exists (
        select 1
        from public.profiles
        where profiles.id = (select auth.uid())
          and profiles.role = 'employee'
    )
);

create policy "Managers and admins can view attendance"
on public.attendance
for select
to authenticated
using (
    exists (
        select 1
        from public.profiles
        where profiles.id = (select auth.uid())
          and profiles.role in ('manager', 'admin')
    )
);

comment on table public.attendance is
'Centralized employee attendance records for TimeTrack.';